export const films = [
{id:1,title:'Интерстеллар',original:'Interstellar',year:2014,genre:'Фантастика',minutes:169,rating:8.7,director:'Кристофер Нолан',moods:['wonder','deep'],symbol:'◉',colors:['#8a9a96','#263a46'],caption:'Любовь за пределами времени',description:'Когда Земля становится непригодной для жизни, команда исследователей отправляется через червоточину искать новый дом для человечества. Масштабное путешествие о времени, семье и надежде.'},
{id:2,title:'Отель «Гранд Будапешт»',original:'The Grand Budapest Hotel',year:2014,genre:'Комедия',minutes:99,rating:8.1,director:'Уэс Андерсон',moods:['light','cozy'],symbol:'♜',colors:['#de998f','#733e53'],caption:'Идеальный побег от рутины',description:'Легендарный консьерж и его юный помощник оказываются в центре истории о похищенной картине и огромном наследстве. Ироничное приключение в узнаваемых пастельных декорациях.'},
{id:3,title:'Дюна: Часть вторая',original:'Dune: Part Two',year:2024,genre:'Фантастика',minutes:166,rating:8.5,director:'Дени Вильнёв',moods:['wonder','thrill'],symbol:'☀',colors:['#d5a468','#684d34'],caption:'Судьба написана в песках',description:'Пол Атрейдес объединяется с фременами и должен сделать выбор между любовью и судьбой целой вселенной. Эпическое кино о власти, пророчествах и цене мести.'},
{id:4,title:'Ла-Ла Ленд',original:'La La Land',year:2016,genre:'Мелодрама',minutes:128,rating:8.0,director:'Дэмьен Шазелл',moods:['romance','light'],symbol:'♫',colors:['#5767ad','#27294e'],caption:'Тем, кто продолжает мечтать',description:'Актриса и джазовый музыкант встречаются в Лос-Анджелесе. Они поддерживают мечты друг друга, но успех меняет их отношения. Музыкальная история любви и выбора.'},
{id:5,title:'Достать ножи',original:'Knives Out',year:2019,genre:'Детектив',minutes:130,rating:7.9,director:'Райан Джонсон',moods:['thrill','light'],symbol:'♠',colors:['#ac965a','#3d3927'],caption:'У каждого есть свой секрет',description:'После смерти известного писателя детектив Бенуа Блан изучает запутанные отношения его семьи. Остроумный детектив, в котором у каждого есть мотив.'},
{id:6,title:'Душа',original:'Soul',year:2020,genre:'Анимация',minutes:100,rating:8.0,director:'Пит Доктер',moods:['cozy','deep'],symbol:'✧',colors:['#72bdb7','#264a50'],caption:'Жизнь происходит прямо сейчас',description:'Джазовый пианист получает долгожданный шанс выступить на сцене, но неожиданно оказывается в мире душ. Тёплая история о поиске смысла в обычных мгновениях.'},
{id:7,title:'Прибытие',original:'Arrival',year:2016,genre:'Фантастика',minutes:116,rating:7.9,director:'Дени Вильнёв',moods:['deep','wonder'],symbol:'⬭',colors:['#8b9f87','#344239'],caption:'Понять — значит изменить всё',description:'Лингвист пытается установить контакт с прибывшими на Землю существами. Знакомство с их языком меняет её представление о времени и собственной жизни.'},
{id:8,title:'Амели',original:'Amélie',year:2001,genre:'Мелодрама',minutes:122,rating:8.3,director:'Жан-Пьер Жёне',moods:['cozy','romance'],symbol:'♥',colors:['#8d9f52','#38533a'],caption:'Маленькие чудеса большого города',description:'Застенчивая парижанка решает незаметно менять жизни окружающих к лучшему. Но чтобы найти собственное счастье, ей предстоит набраться смелости.'},
{id:9,title:'Безумный Макс: Дорога ярости',original:'Mad Max: Fury Road',year:2015,genre:'Боевик',minutes:120,rating:8.1,director:'Джордж Миллер',moods:['thrill'],symbol:'⚡',colors:['#d89345','#65371e'],caption:'Только вперёд',description:'В постапокалиптической пустыне Макс присоединяется к Фуриосе, которая спасает пленниц жестокого правителя. Захватывающая погоня с впечатляющими практическими эффектами.'},
{id:10,title:'Патерсон',original:'Paterson',year:2016,genre:'Драма',minutes:118,rating:7.3,director:'Джим Джармуш',moods:['cozy','deep'],symbol:'☷',colors:['#8caaa9','#42525a'],caption:'Поэзия каждого дня',description:'Водитель автобуса пишет стихи, гуляет с собакой и слушает разговоры пассажиров. Семь тихих дней, которые помогают увидеть красоту повседневной жизни.'},
{id:11,title:'Назад в будущее',original:'Back to the Future',year:1985,genre:'Приключения',minutes:116,rating:8.5,director:'Роберт Земекис',moods:['light','wonder'],symbol:'↯',colors:['#698cb4','#403069'],caption:'Твоё будущее ещё не написано',description:'Марти Макфлай случайно попадает в прошлое на машине времени и мешает знакомству собственных родителей. Теперь нужно исправить историю и вернуться домой.'},
{id:12,title:'Перед рассветом',original:'Before Sunrise',year:1995,genre:'Мелодрама',minutes:101,rating:8.1,director:'Ричард Линклейтер',moods:['romance','deep'],symbol:'☾',colors:['#af857a','#514249'],caption:'Одна ночь. Тысяча разговоров.',description:'Двое незнакомцев встречаются в поезде и проводят ночь, гуляя по Вене. Фильм о неожиданной близости, разговорах и мимолётности счастливых моментов.'}
];
export function selectFilms({mood='all',query='',genre='',duration=0,savedOnly=false,saved=[]}={}){const q=query.trim().toLocaleLowerCase('ru');return films.filter(f=>(mood==='all'||f.moods.includes(mood))&&(!q||`${f.title} ${f.original} ${f.director}`.toLocaleLowerCase('ru').includes(q))&&(!genre||f.genre===genre)&&(!Number(duration)||f.minutes<=Number(duration))&&(!savedOnly||saved.includes(f.id)));}
const moodOptions=[['all','✦','Всё хорошее'],['cozy','☕','Уютный вечер'],['thrill','⚡','Хочу адреналина'],['deep','◈','Есть о чём подумать'],['romance','♡','Влюбиться'],['light','☺','Что-то лёгкое'],['wonder','✧','Удиви меня']];
if(typeof document!=='undefined'){
const $=id=>document.getElementById(id);let mood='all',savedOnly=false,saved=[],tab='discover',reactions={};try{const raw=JSON.parse(localStorage.getItem('nightshift.reactions')||'{}');if(raw&&typeof raw==='object'&&!Array.isArray(raw))reactions=raw;}catch{}try{const raw=JSON.parse(localStorage.getItem('afterglow.saved')||'[]');if(Array.isArray(raw))saved=raw.filter(id=>films.some(f=>f.id===id));}catch{}let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2300);}
function toggleSave(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];try{localStorage.setItem('afterglow.saved',JSON.stringify(saved));}catch{toast('Браузер не разрешает сохранение. Список доступен в этой сессии.');}render();if($('details').open)showDetails(id);}
function score(f){let value=0;for(const other of films){const r=reactions[other.id];if(r==='like'||r==='dislike'){const sign=r==='like'?1:-1;value+=sign*(f.genre===other.genre?3:0);value+=sign*f.moods.filter(m=>other.moods.includes(m)).length;}}return value;}
function react(id,value){if(reactions[id]===value)delete reactions[id];else reactions[id]=value;try{localStorage.setItem('nightshift.reactions',JSON.stringify(reactions));}catch{toast('Оценки доступны только в этой сессии.');}render();showDetails(id);}
function current(){let list=selectFilms({mood,query:$('search').value,genre:$('genre').value,duration:$('duration').value,savedOnly:tab==='queue',saved});list=list.filter(f=>tab==='favorites'?reactions[f.id]==='like':tab==='archive'?['watched','dislike'].includes(reactions[f.id]):!['watched','dislike'].includes(reactions[f.id]));return list.sort((a,b)=>$('sort').value==='year'?b.year-a.year:$('sort').value==='rating'?b.rating-a.rating:score(b)-score(a)||b.rating-a.rating);}
function showDetails(id){const f=films.find(f=>f.id===id);$('detail-content').innerHTML=`<div class="eyebrow">${f.original} · ${f.year}</div><h2>${f.title}</h2><div class="detail-meta">★ ${f.rating.toFixed(1)} · ${f.genre} · ${f.minutes} мин.</div><p>${f.description}</p><p>Режиссёр: ${f.director}</p><div class="reaction-buttons">${[['like','♡ Нравится'],['dislike','− Не моё'],['watched','✓ Просмотрено']].map(([v,t])=>`<button class="secondary ${reactions[id]===v?'chosen':''}" data-reaction="${v}" aria-pressed="${reactions[id]===v}">${t}</button>`).join('')}</div><button class="primary" id="detail-save">${saved.includes(id)?'✓ В моём списке — убрать':'+ Посмотреть позже'}</button><p style="font-size:10px">Оценка IMDb указана справочно и не обновляется автоматически. Это локальная подборка; просмотр фильмов на сайте не предоставляется.</p>`;$('detail-save').onclick=()=>toggleSave(id);document.querySelectorAll('[data-reaction]').forEach(b=>b.onclick=()=>react(id,b.dataset.reaction));if(!$('details').open)$('details').showModal();}
function render(){const list=current();$('count').textContent=saved.length;$('section-title').textContent=({discover:'Подобрать фильм',queue:'На просмотр',favorites:'Избранное',archive:'Архив'})[tab];$('tabs').innerHTML=[['discover','Подбор'],['queue','На просмотр'],['favorites','Избранное'],['archive','Архив']].map(([v,t])=>`<button class="tab ${tab===v?'active':''}" data-tab="${v}" aria-pressed="${tab===v}">${t}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});const rated=Object.values(reactions).filter(r=>r==='like'||r==='dislike').length;$('taste-summary').textContent=rated?`Оценок: ${rated}. Подбор учитывает любимые жанры и настроение фильмов.`:'Оцени несколько фильмов — и начнём узнавать твой вкус.';$('saved').style.color=savedOnly?'var(--accent)':'';$('result-count').textContent=`Найдено фильмов: ${list.length}`;$('empty').hidden=list.length>0;$('films').innerHTML=list.map(f=>`<article class="film"><div class="poster" style="--c1:${f.colors[0]};--c2:${f.colors[1]}" data-detail="${f.id}" tabindex="0" role="button" aria-label="Подробнее: ${f.title}"><span class="rating">★ ${f.rating.toFixed(1)}</span><button class="save ${saved.includes(f.id)?'selected':''}" data-save="${f.id}" aria-label="${saved.includes(f.id)?'Убрать из списка':'Сохранить'}: ${f.title}" aria-pressed="${saved.includes(f.id)}">${saved.includes(f.id)?'✓':'+'}</button><span class="poster-art">${f.symbol}</span><div class="poster-title">${f.original}<span class="poster-caption">${f.caption}</span></div></div><h3>${f.title}</h3><p>${f.year} · ${f.genre} · ${f.minutes} мин.</p><span class="tag">${moodOptions.find(m=>m[0]===f.moods[0])[2]}</span></article>`).join('');document.querySelectorAll('[data-save]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleSave(Number(b.dataset.save));});document.querySelectorAll('[data-detail]').forEach(b=>{b.onclick=()=>showDetails(Number(b.dataset.detail));b.onkeydown=e=>{if(e.target===b&&['Enter',' '].includes(e.key)){e.preventDefault();showDetails(Number(b.dataset.detail));}};});document.querySelectorAll('[data-mood]').forEach(b=>{b.classList.toggle('active',b.dataset.mood===mood);b.setAttribute('aria-pressed',String(b.dataset.mood===mood));});}
$('moods').innerHTML=moodOptions.map(([id,icon,title])=>`<button class="mood" data-mood="${id}">${icon} &nbsp; ${title}</button>`).join('');document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{mood=b.dataset.mood;render();});[...new Set(films.map(f=>f.genre))].sort().forEach(g=>{const o=document.createElement('option');o.value=g;o.textContent=g;$('genre').append(o);});['search','genre','duration','sort'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('reset').onclick=()=>{mood='all';$('search').value='';$('genre').value='';$('duration').value='0';render();};$('saved').onclick=()=>{tab=tab==='queue'?'discover':'queue';savedOnly=tab==='queue';render();$('discover').scrollIntoView({behavior:'smooth'});};$('random').onclick=()=>{const list=current();if(!list.length){toast('Нет фильмов для этих фильтров. Попробуй сбросить их.');return;}showDetails(list[Math.floor(Math.random()*list.length)].id);};$('clear-taste').onclick=()=>{reactions={};try{localStorage.removeItem('nightshift.reactions');}catch{}render();toast('Оценки сброшены');};$('close').onclick=()=>$('details').close();$('details').addEventListener('click',e=>{if(e.target===$('details')){const r=$('details').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('details').close();}});render();
}
